# Electronics Store Configuration
db.driverName=com.mysql.cj.jdbc.Driver
db.connectionString=jdbc:mysql://localhost:3306/shopping-cart?useSSL=false&allowPublicKeyRetrieval=true
db.username=root
db.password=

mailer.email=your_email@gmail.com
mailer.password=your_16_digit_app_password


